## Configuracion de Spring
spring:
  application:
    name: bbdda-grupal-spring-data
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/eess} #Actualizar con el valor de tu despliegue local de MySQL.
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
    username: ${DB_USER:root} #Actualizar con el valor de tu usuario.
    password: ${DB_PASSWORD:mysql} #Actualizar con el valor de tu contraseña de root.
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      ##update

## Configuracion de Instancia 
server:
  port: 8088

## Configuracion de Elasticsearch
elasticsearch:
  host: ${ELASTICSEARCH_HOST:g7-bbdda-3996498811.eu-west-1.bonsaisearch.net}
  credentials:
    username: ${ELASTICSEARCH_USERNAME:b2kmmqoh4l}
    password: ${ELASTICSEARCH_PASSWORD:1vvnt2zmot}
logging:
  level:
    tracer: TRACE
